# ============================================================
# backend/models/feedback_model.py
#
# This is a reference schema doc — MongoDB is schema-less so
# we don't enforce it strictly, but this shows the exact
# structure every feedback document should have.
# ============================================================

"""
feedbacks collection — document structure:

{
    "_id":           ObjectId,           # auto-generated by MongoDB
    "user_id":       str,                # user's _id as string
    "userName":      str,                # e.g. "Cheenu Singh"
    "userEmail":     str,                # e.g. "cheenu103@gmail.com"

    "ratings": {                         # per-section ratings
        "Mock Tests":              str,  # "Excellent"|"Good"|"Average"|"Bad"|"Worst"
        "PYQ / Previous Papers":   str,
        "College Listings":        str,
        "Overall Experience":      str,
        # add more categories as needed
    },

    "overallRating": str,                # derived from ratings (most common value)
    "suggestion":    str,                # free-text suggestion from user
    "createdAt":     str,                # ISO 8601 UTC datetime string
}
"""


# ── Validation helper (optional — call before insert if you want) ──
VALID_RATINGS = {"Excellent", "Good", "Average", "Bad", "Worst"}

def validate_feedback(data: dict) -> tuple[bool, str]:
    """Returns (is_valid, error_message)."""
    if not data.get("user_id"):
        return False, "user_id is required"

    ratings = data.get("ratings", {})
    for category, rating in ratings.items():
        if rating not in VALID_RATINGS:
            return False, f"Invalid rating '{rating}' for category '{category}'"

    overall = data.get("overallRating", "")
    if overall and overall not in VALID_RATINGS:
        return False, f"Invalid overallRating: {overall}"

    return True, ""


# ── MongoDB index recommendations ──────────────────────────
# Run these once in your DB setup / seed script:
#
# mongo.db.feedbacks.create_index("user_id")
# mongo.db.feedbacks.create_index("overallRating")
# mongo.db.feedbacks.create_index([("createdAt", -1)])
